#!/usr/bin/env python3
"""
Build universe_nse100.py — the NSE-100 trading universe for the Sniper Agent.

Resolves official NSE_EQ instrument keys (ISIN-based) from Upstox's public
instruments file, so no ISIN is ever hand-typed. A wrong ISIN fails silently
forever; a wrong trading symbol below fails LOUDLY here — that asymmetry is
the whole point of this script.

Usage (one time, or whenever you edit the lists):
    python3 build_universe.py
    # review the printed summary, then restart the agent

Output: universe_nse100.py next to allstrategy.py — first list has
has_options=True (options-fed evidence plane), second list has_options=False
(structure-only path). Edit the lists to taste; index composition changes a
couple of times a year, and any symbol that no longer resolves is reported
instead of silently dropped.
"""
import gzip
import io
import json
import sys
from datetime import datetime
from pathlib import Path

import requests

INSTRUMENTS_URL = ("https://assets.upstox.com/market-quote/instruments/"
                   "exchange/NSE.json.gz")
OUT = Path(__file__).resolve().parent / "universe_nse100.py"

# --- EDIT HERE: 50 options-fed symbols (Nifty 50) ---------------------------------
OPTIONS_FED = [
    "RELIANCE", "HDFCBANK", "ICICIBANK", "INFY", "TCS",
    "BHARTIARTL", "ITC", "LT", "SBIN", "AXISBANK",
    "KOTAKBANK", "HINDUNILVR", "BAJFINANCE", "MARUTI", "M&M",
    "SUNPHARMA", "NTPC", "HCLTECH", "ULTRACEMCO", "TITAN",
    "POWERGRID", "TATAMOTORS", "TATASTEEL", "ASIANPAINT", "BAJAJFINSV",
    "ONGC", "COALINDIA", "ADANIENT", "ADANIPORTS", "WIPRO",
    "NESTLEIND", "GRASIM", "JSWSTEEL", "TECHM", "INDUSINDBK",
    "HINDALCO", "DRREDDY", "CIPLA", "EICHERMOT", "BAJAJ-AUTO",
    "TATACONSUM", "APOLLOHOSP", "SBILIFE", "HDFCLIFE", "BRITANNIA",
    "HEROMOTOCO", "BPCL", "SHRIRAMFIN", "BEL", "TRENT",
]
# --- EDIT HERE: 50 structure-only symbols (Nifty Next 50) --------------------------
STRUCTURE_ONLY = [
    "ABB", "ADANIENSOL", "ADANIGREEN", "ADANIPOWER", "AMBUJACEM",
    "BAJAJHLDNG", "BANKBARODA", "BHEL", "BOSCHLTD", "CANBK",
    "CHOLAFIN", "DABUR", "DIVISLAB", "DLF", "GAIL",
    "GODREJCP", "HAVELLS", "HAL", "ICICIGI", "ICICIPRULI",
    "IOC", "INDIGO", "IRCTC", "IRFC", "JINDALSTEL",
    "JIOFIN", "LICI", "LODHA", "LTIM", "MOTHERSON",
    "NAUKRI", "PIDILITIND", "PFC", "PNB", "RECLTD",
    "SIEMENS", "SHREECEM", "TATAPOWER", "TORNTPHARM", "TVSMOTOR",
    "UNITDSPR", "VBL", "VEDL", "ZOMATO", "ZYDUSLIFE",
    "ATGL", "COLPAL", "MARICO", "SRF", "BERGEPAINT",
]
IV_CAPS = {"RELIANCE": 75}          # per-symbol overrides; default 70


def main():
    print(f"[1/3] downloading instruments file ...")
    r = requests.get(INSTRUMENTS_URL, timeout=60)
    r.raise_for_status()
    rows = json.load(io.TextIOWrapper(
        gzip.GzipFile(fileobj=io.BytesIO(r.content)), encoding="utf-8"))
    eq = {row["trading_symbol"]: row["instrument_key"]
          for row in rows
          if row.get("segment") == "NSE_EQ"
          and row.get("instrument_type") == "EQ"}
    print(f"      {len(eq)} NSE_EQ equities in file")

    print("[2/3] resolving universe ...")
    universe, missing = {}, []
    for syms, has_opts in ((OPTIONS_FED, True), (STRUCTURE_ONLY, False)):
        for s in syms:
            key = eq.get(s)
            if key is None:
                missing.append(s)
                continue
            universe[key] = {"symbol": s, "iv_cap": IV_CAPS.get(s, 70),
                             "has_options": has_opts}
    if missing:
        print("\n  !! UNRESOLVED SYMBOLS (renamed/delisted — fix the lists):")
        for s in missing:
            print(f"     - {s}")
        print("  Tip: search the file for the company, e.g.\n"
              "     python3 -c \"import json,gzip;"
              "print([r['trading_symbol'] for r in json.load(gzip.open("
              "'NSE.json.gz')) if 'KEYWORD' in r.get('name','')])\"")

    n_opt = sum(1 for v in universe.values() if v["has_options"])
    print(f"[3/3] writing {OUT.name}: {len(universe)} symbols "
          f"({n_opt} options-fed, {len(universe) - n_opt} structure-only)")
    lines = [
        '"""Auto-generated by build_universe.py — do not hand-edit ISINs.',
        f'Generated {datetime.now().isoformat()} from {INSTRUMENTS_URL}',
        f'{len(universe)} symbols; edit the lists in build_universe.py and',
        'regenerate to change composition."""', "",
        "UNIVERSE = {",
    ]
    for key, cfg in universe.items():
        lines.append(
            f'    "{key}": {{"symbol": "{cfg["symbol"]}", '
            f'"iv_cap": {cfg["iv_cap"]}, '
            f'"has_options": {cfg["has_options"]}}},')
    lines += ["}", ""]
    OUT.write_text("\n".join(lines))
    print(f"\nDone. {len(universe)} symbols written"
          + (f"; {len(missing)} MISSING — fix and re-run." if missing
             else " — all resolved."))
    print("Restart the agent; it will print "
          "'[UNIVERSE] universe_nse100.py loaded: ...' on startup.")
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
