#!/usr/bin/env python3
"""
Build universe_nse500.py — Nifty 500 equity universe for marketdata fetch.

Downloads the official NSE Nifty 500 constituent CSV and resolves each
symbol to an Upstox NSE_EQ instrument key (ISIN-based).

Usage:
    python3 build_universe_nse500.py

Output: universe_nse500.py next to this script.
"""
import csv
import gzip
import io
import json
import sys
from datetime import datetime
from pathlib import Path

import requests

NIFTY500_CSV = ("https://nsearchives.nseindia.com/content/indices/"
                "ind_nifty500list.csv")
INSTRUMENTS_URL = ("https://assets.upstox.com/market-quote/instruments/"
                   "exchange/NSE.json.gz")
OUT = Path(__file__).resolve().parent / "universe_nse500.py"
IV_CAPS = {"RELIANCE": 75}

# Nifty 50 symbols — marked has_options=True for SmartAgent compatibility.
NIFTY50 = {
    "RELIANCE", "HDFCBANK", "ICICIBANK", "INFY", "TCS",
    "BHARTIARTL", "ITC", "LT", "SBIN", "AXISBANK",
    "KOTAKBANK", "HINDUNILVR", "BAJFINANCE", "MARUTI", "M&M",
    "SUNPHARMA", "NTPC", "HCLTECH", "ULTRACEMCO", "TITAN",
    "POWERGRID", "TATASTEEL", "ASIANPAINT", "BAJAJFINSV",
    "ONGC", "COALINDIA", "ADANIENT", "ADANIPORTS", "WIPRO",
    "NESTLEIND", "GRASIM", "JSWSTEEL", "TECHM", "INDUSINDBK",
    "HINDALCO", "DRREDDY", "CIPLA", "EICHERMOT", "BAJAJ-AUTO",
    "TATACONSUM", "APOLLOHOSP", "SBILIFE", "HDFCLIFE", "BRITANNIA",
    "HEROMOTOCO", "BPCL", "SHRIRAMFIN", "BEL", "TRENT",
}


def _load_nifty500_symbols():
    r = requests.get(NIFTY500_CSV, timeout=60,
                     headers={"User-Agent": "Mozilla/5.0"})
    r.raise_for_status()
    rows = list(csv.DictReader(io.StringIO(r.text)))
    symbols = [row["Symbol"].strip().upper() for row in rows if row.get("Symbol")]
    return symbols, rows


def main():
    print(f"[1/3] downloading Nifty 500 CSV ...")
    symbols, rows = _load_nifty500_symbols()
    print(f"      {len(symbols)} symbols in CSV")

    print(f"[2/3] downloading Upstox instruments ...")
    r = requests.get(INSTRUMENTS_URL, timeout=60)
    r.raise_for_status()
    inst = json.load(io.TextIOWrapper(
        gzip.GzipFile(fileobj=io.BytesIO(r.content)), encoding="utf-8"))
    eq = {row["trading_symbol"]: row["instrument_key"]
          for row in inst
          if row.get("segment") == "NSE_EQ"
          and row.get("instrument_type") == "EQ"}
    print(f"      {len(eq)} NSE_EQ equities in Upstox file")

    print("[3/3] resolving universe ...")
    universe, missing = {}, []
    for sym in symbols:
        key = eq.get(sym)
        if key is None:
            missing.append(sym)
            continue
        universe[key] = {
            "symbol": sym,
            "iv_cap": IV_CAPS.get(sym, 70),
            "has_options": sym in NIFTY50,
        }

    if missing:
        print("\n  !! UNRESOLVED SYMBOLS:")
        for s in missing:
            print(f"     - {s}")

    n_opt = sum(1 for v in universe.values() if v["has_options"])
    print(f"      writing {OUT.name}: {len(universe)} symbols "
          f"({n_opt} options-fed)")

    lines = [
        '"""Auto-generated by build_universe_nse500.py — do not hand-edit ISINs.',
        f'Generated {datetime.now().isoformat()} from {NIFTY500_CSV}',
        f'{len(universe)} symbols; re-run build_universe_nse500.py to refresh."""',
        "",
        "UNIVERSE = {",
    ]
    for key, cfg in universe.items():
        lines.append(
            f'    "{key}": {{"symbol": "{cfg["symbol"]}", '
            f'"iv_cap": {cfg["iv_cap"]}, '
            f'"has_options": {cfg["has_options"]}}},')
    lines += ["}", ""]
    OUT.write_text("\n".join(lines))
    print(f"\nDone. {len(universe)} symbols written"
          + (f"; {len(missing)} MISSING." if missing else " — all resolved."))
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
