"""
RealBackTest configuration — universe, dates, paths, reconstruction params.

Everything the harness, data layer and IV engine need in one place so a run
is reproducible from this file + the cache DB.
"""
import os
import sqlite3
import sys
import tempfile
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent          # RealBackTest/
REPO = BASE.parent                                     # SniperAgent/ (shared root)
sys.path.insert(0, str(REPO))
from shared_data import market_data_db, market_data_dir  # noqa: E402


def _sqlite_ok(d):
    """
    Test that SQLite WAL mode works in directory d.
    Synced/cloud folders (iCloud, Dropbox, OneDrive) often pass a basic
    connect() but fail on WAL journal creation or executemany() for large
    files — this probe catches both failure modes.
    """
    try:
        d.mkdir(parents=True, exist_ok=True)
        p = d / ".sqlite_probe"
        conn = sqlite3.connect(str(p))
        conn.execute("PRAGMA journal_mode=WAL")   # same mode Cache uses
        conn.execute("CREATE TABLE IF NOT EXISTS t (x INTEGER)")
        conn.executemany("INSERT INTO t VALUES (?)", [(i,) for i in range(50)])
        conn.commit()
        conn.close()
        p.unlink(missing_ok=True)
        # Also remove WAL/SHM sidecar files left by the probe
        for suf in ("-wal", "-shm"):
            (d / (p.name + suf)).unlink(missing_ok=True)
        return True
    except Exception:
        return False


def _pick(env, preferred, fallback_name):
    if os.environ.get(env):
        return Path(os.environ[env])
    if _sqlite_ok(preferred):
        return preferred
    alt = Path(tempfile.gettempdir()) / fallback_name
    alt.mkdir(parents=True, exist_ok=True)
    print(f"[CONFIG] {preferred} cannot host SQLite (synced folder?) — "
          f"using {alt} (override with {env})")
    return alt


# Shared market data DB — accessible to SmartAgent, RealBackTest, PriceActionAgent.
# Default: Data.nosync/marketdata.db (see shared_data.py).
DATA_DIR = market_data_dir()
CACHE_DB = market_data_db()

# RealBackTest-specific runtime artifacts (run engine DBs and reports).
# Override: RBT_DB_DIR=/path  RBT_REPORT_DIR=/path
DB_DIR     = _pick("RBT_DB_DIR",
                   REPO / "Data" / "RealBackTest" / "db", "rbt_db")
REPORT_DIR = Path(os.environ.get("RBT_REPORT_DIR",
                                 str(REPO / "Data" / "RealBackTest" / "reports")))

# --- backtest window (override on CLI) -----------------------------------------
DEFAULT_START = "2024-06-01"
DEFAULT_END = "2026-06-10"

# --- universe: mirrors SmartAgent/allstrategy.py UNIVERSE exactly ---------------
# has_options=True symbols get the reconstructed options plane (real OI/premium
# from Upstox expired-instrument candles); the rest run structure-only, same
# as live. If SmartAgent/universe_nse100.py exists (generated by
# build_universe.py), it replaces the default 5-symbol universe — keeping
# backtest and live on the same playing field.
_DEFAULT_UNIVERSE = [
    {"symbol": "RELIANCE",  "instrument_key": "NSE_EQ|INE002A01018",
     "iv_cap": 75, "has_options": True},
    {"symbol": "HDFCBANK",  "instrument_key": "NSE_EQ|INE040A01034",
     "iv_cap": 70, "has_options": True},
    {"symbol": "ICICIBANK", "instrument_key": "NSE_EQ|INE090A01021",
     "iv_cap": 70, "has_options": True},
    {"symbol": "TCS",       "instrument_key": "NSE_EQ|INE467B01029",
     "iv_cap": 70, "has_options": False},
    {"symbol": "SBIN",      "instrument_key": "NSE_EQ|INE062A01020",
     "iv_cap": 70, "has_options": False},
]


def _load_universe():
    """Load universe from SmartAgent/universe_*.py (env RBT_UNIVERSE selects file)."""
    name = os.environ.get("RBT_UNIVERSE", "nse100").strip().lower()
    candidates = {
        "nse100": REPO / "SmartAgent" / "universe_nse100.py",
        "nse500": REPO / "SmartAgent" / "universe_nse500.py",
    }
    gen = candidates.get(name) or Path(name)
    if not gen.is_file():
        print(f"[CONFIG] universe file not found: {gen} — using default 5-symbol")
        return _DEFAULT_UNIVERSE
    ns = {}
    exec(gen.read_text(), ns)
    uni = [{"symbol": v["symbol"], "instrument_key": k,
            "iv_cap": v["iv_cap"], "has_options": v["has_options"]}
           for k, v in ns["UNIVERSE"].items()]
    n_opt = sum(1 for u in uni if u["has_options"])
    print(f"[CONFIG] {gen.name} loaded: {len(uni)} symbols "
          f"({n_opt} options-fed)")
    return uni


def get_universe():
    """Fresh universe load (respects RBT_UNIVERSE env set after import)."""
    return _load_universe()


UNIVERSE = _load_universe()

# --- pre-window history needed so every horizon has full lookback on day 1 -----
# (live engine fetches: 30m 20d, daily 300d, weekly 750d)
PREFETCH_DAYS = {"30m": 45, "daily": 450, "weekly": 1100}

# --- IV reconstruction -----------------------------------------------------------
RISK_FREE_RATE = 0.065        # annualised; RBI repo-rate neighbourhood
IV_EWMA_LAMBDA = 0.80         # smoothing of the recovered per-bar IV
IV_JUMP_CAP_PTS = 8.0         # reject one-bar IV jumps > this many vol points
IV_MIN_PCT, IV_MAX_PCT = 1.0, 300.0
EXPIRY_CLOSE_HM = (15, 30)    # option settles at 15:30 IST on expiry day

# --- options as-of staleness caps (seconds) --------------------------------------
# Option 1-min candles are sparse for illiquid minutes; we use backward as-of
# joins. If the freshest option bar is older than this, the options plane is
# declared unavailable for that evaluation (engine then runs structure-only
# with the P_STAR_NO_OPTIONS floor — exactly the live degradation path).
OPT_STALENESS_S = 900         # 15 minutes

# --- BVC flow proxy ---------------------------------------------------------------
# Bulk Volume Classification (Easley, Lopez de Prado, O'Hara 2012): split each
# option bar's volume into buy/sell using the CDF of its standardised price
# change. Aggregated over a trailing window and presented to the engine as
# bid_qty / ask_qty so x6 = ln(bid/ask) becomes ln(V_buy / V_sell).
FLOW_WINDOW_BARS = 5          # trailing ATM-CE bars aggregated
FLOW_SIGMA_LAMBDA = 0.94      # EWMA of |dClose| used to standardise

# --- strike pre-selection for the fetch ------------------------------------------
# For each expiry's active window we fetch only strikes that are ATM on at
# least one session (daily close nearest strike) plus this many neighbours
# each side — covers intraday wander without downloading the whole chain.
STRIKE_NEIGHBOURS = 4   # was 2: HDFCBANK intraday spot wandered past the
                        # cached strikes (33% availability, IV 82.6%) —
                        # wider net fixes staleness; refetch is incremental

# --- fetch throttling -------------------------------------------------------------
# Upstox caps: 50 req/s, 500 req/min AND 2000 req per 30 min. The 30-min
# quota is the binding one for a long options fetch: 2000/1800s ~ 1.11 req/s
# sustained. Stay just under it.
REQS_PER_SEC = 1.05
MAX_RETRIES = 5          # for transient 5xx
RATE_LIMIT_WAITS = 12    # 429s: patient waits (quota window), not failures
TIMEOUT_S = 20

# --- assessment thresholds (go/no-go) ----------------------------------------------
GO_CRITERIA = {
    "min_trades_per_claim": 30,      # horizons below this: "insufficient data"
    "bootstrap_p_max": 0.05,         # mean R > 0 significance
    "random_entry_pctile_min": 95.0, # must beat this pctile of random entries
    "iv_recovery_min": 0.90,         # fraction of option-active bars with IV
    "maxdd_frac_capital_max": 0.10,  # max drawdown vs CAPITAL
    "dsr_min": 0.0,                  # deflated Sharpe must stay positive
}

COST_BPS_DEFAULT = 10.0
